#!/bin/sh

mkdir output 2>/dev/null
mkdir d64 2>/dev/null


DISK="$1"
####rsync --progress -v -a pi@192.168.99.8:/home/pi/pub/floppy/bbc-fdc/tools/out/disk${DISK}*-*.rfi  ../out/
#scp -rp pi@192.168.99.3:/home/pi/pub/floppy/bbc-fdc/tools/out/disk${DISK}*-*.rfi ../out/
./ripit1 "??" "?" ../out/disk${DISK}*-*.rfi | tee -a  output/o${DISK}
./fm41fix | tee work/fm.out
TAG=`grep "Status:" work/fm.out | sed "s/Status: //"`
cat work/fm.out >> output/o${DISK}
D64=d64/data${DISK}-201902xx-auto-$TAG.d64
cat data/track*dat >$D64
c1541 $D64 -dir > ${DISK}-dir.txt

mkdir -p extract/e${DISK} 2>/dev/null
cd extract/e${DISK}
if [ $? -ne 0 ]
then
	exit 1
fi
cp -p ../../1.png ${DISK}.png

mv ../../${DISK}-dir.txt .
cat ${DISK}-dir.txt 

c1541 ../../$D64 -extract

if [ 1 -eq 0 ]
then
	cd ..
	cd g64
	if [ $? -ne 0 ]
	then
		exit 2
	fi
	
	make g64cr && ./g64cr >${DISK}.auto-$TAG.g64 2>2
fi

echo "done"
#######
# END #
#######
