#!/bin/sh
cd src
make
make bbcfdc-nopi # if required
make bbcfdc_pc # if required
gcc -odisplay displaymain.c display.c
cd ..
ln -s src/bbcfdc
ln -s src/bbcfdc_pc # if required
ln -s src/bbcfdc-nopi # if required
ln -s src/checkfsd
ln -s src/display
ln -s src/drivetest
# need to build the decoder first, and the link needs to be in place
ln -s ../../r15

