#!/bin/sh

#rm -f bitmap.dat 2>/dev/null

./r15 track.rle 1>r1 2>r2 010 0 -1 -1 0 0 0 0 $1 
tail -1 r2 ; tail -1 r2>>coll

./r15 track.rle 1>r1 2>r2 003 0 -1 -1 0 0 0 0 $1 
tail -1 r2 ; tail -1 r2>>coll

