#!/bin/sh

#rm -f bitmap.dat 2>/dev/null
# test
if [ $1 -gt 35 ]
then
	REVERSED=1
	# guessing the track is:
	TRACK=`expr $1 + 4 - 36 + 1`
	echo "reversed $1 -> $TRACK">>aa
else
	REVERSED=0
	TRACK=$1
fi

./r15 track.rle 1>r1 2>r2 010 0 -1 -1 0 0 0 0 $TRACK $REVERSED
tail -1 r2 ; tail -1 r2>>coll

./r15 track.rle 1>r1 2>r2 003 0 -1 -1 0 0 0 0 $TRACK $REVERSED
tail -1 r2 ; tail -1 r2>>coll

